#!/bin/bash

re="^([0-9]{3}|-|w|a|s|d)$"
num="^([0-9]{2})$"

function getPage() {
  local currentPage=$page
  read -rn1 -p "($currentPage)Page: " page
  if ! [[ "${page}" =~ ${re} ]]; then
    read -rn2 rest
    if [[ "${rest}" =~ ${num} ]]; then
      let "hundred=page*100"
      let "page=hundred+rest"
      side=1
    fi
  fi
  if ! [[ "${page}" =~ ${re} ]]; then
    echo -e "\033[2K"
    tput cuu 1
    let "page=currentPage"
    getPage
    fi
  if [ $page = '-' ]; then
    page=$prevPage
    side=1
  fi
  if [ $page = 'w' ];
  then
   let "page=currentPage"
   side=1
  fi
  if [ $page = 'a' ];
  then
   let "page=currentPage-1"
   side=1
  fi
  if [ $page = 's' ];
  then
   let "page=currentPage"
   side=2
  fi
  if [ $page = 'd' ];
  then
   let "page=currentPage+1"
   side=1
  fi
  prevPage=$currentPage
}

printf "\033c"

page=100
side=1
#url="curl 'https://www.nrk.no/teletextresources/${page}.1-w500.gif' -s --output - | viu -s -"
#url="kitty +kitten icat https://www.nrk.no/teletextresources/${page}.1-w500.gif"

while true; do
  kitty +kitten icat https://www.nrk.no/teletextresources/${page}.${side}-w500.gif
  getPage
  printf "\033c"
done
